import type { DisplayTransaction } from '../types'

/** Користувацький контекст фікстури: EUR, бюджет 3400, monthStartDay 6 */
export const MOCK_USER_CONTEXT = {
  currency: 'EUR',
  monthlyBudget: 3400,
  monthStartDay: 6,
}

export const mockTransactions: DisplayTransaction[] = [
  {
    id: '1',
    amount: 5,
    currency: 'EUR',
    originalAmount: 6,
    originalCurrency: 'USD',
    categoryId: 'work--subscriptions',
    description: 'JetBrains',
    date: new Date(2026, 5, 3),
    createdAt: new Date(2026, 5, 3, 10, 0),
    planningId: null,
  },
  {
    id: '2',
    amount: 52,
    currency: 'EUR',
    categoryId: 'food--food-delivery',
    description: 'Суші',
    date: new Date(2026, 5, 2),
    createdAt: new Date(2026, 5, 2, 19, 30),
    planningId: null,
  },
  {
    id: '3',
    amount: 11,
    currency: 'EUR',
    categoryId: 'food--groceries',
    description: 'Продукти',
    date: new Date(2026, 4, 30),
    createdAt: new Date(2026, 4, 30, 12, 0),
    planningId: null,
  },
  {
    id: '4',
    amount: 2,
    currency: 'EUR',
    categoryId: 'car--parking',
    description: 'Паркінг',
    date: new Date(2026, 4, 28),
    createdAt: new Date(2026, 4, 28, 9, 15),
    planningId: null,
  },
  {
    id: '5',
    amount: 18,
    currency: 'EUR',
    categoryId: 'travel',
    description: 'Книга з кемпінгами',
    date: new Date(2026, 4, 27),
    createdAt: new Date(2026, 4, 27, 14, 0),
    planningId: null,
  },
  {
    id: '6',
    amount: 4,
    currency: 'EUR',
    originalAmount: 5,
    originalCurrency: 'USD',
    categoryId: 'entertainment--subscriptions',
    description: 'Adobe',
    date: new Date(2026, 4, 26),
    createdAt: new Date(2026, 4, 26, 16, 45),
    planningId: null,
  },
  {
    id: '7',
    amount: 18,
    currency: 'EUR',
    categoryId: 'housing--utilities',
    description: 'Вода',
    date: new Date(2026, 4, 26),
    createdAt: new Date(2026, 4, 26, 8, 0),
    planningId: 'plan-1',
  },
]
