type AuthResponse {
  accessToken: String!
  refreshToken: String!
  user: UserWithoutPasswordModel!
}

"""
A date-time string at UTC, such as 2019-12-03T09:54:33Z, compliant with the date-time format.
"""
scalar DateTime

type ExchangeRate {
  _count: ExchangeRateCount!
  base: String!
  date: DateTime!
  id: ID!
  rates: JSON!
  transaction: [Transaction!]
}

type ExchangeRateCount {
  transaction: Int!
}

"""
The `JSON` scalar type represents JSON values as specified by [ECMA-404](http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf).
"""
scalar JSON

type Mutation {
  createPlanning(planningData: PlanningInput!): Planning!
  createTransaction(transactionData: TransactionInput!): Transaction!
  createUser(email: String!, name: String, password: String!): UserWithoutPasswordModel!
  deletePlanning(planningId: Float!): Planning!
  deleteTransaction(id: Float!): Transaction!
  onboarding(onboardingData: OnboardingInput!): UserWithoutPasswordModel!
  refreshTokens(refreshToken: String!): AuthResponse!
  signIn(signInData: SignInInput!): AuthResponse!
  signOut: Boolean!
  signUp(signUpData: SignUpInput!): UserWithoutPasswordModel!
  updatePlanning(planningData: PlanningInput!, planningId: Float!): Planning!
  updateProfile(updateProfileData: UpdateProfileInput!): UserWithoutPasswordModel!
  updateTransaction(id: Float!, transactionData: TransactionInput!): Transaction!
}

input OnboardingInput {
  currency: String!
  monthStartDay: Float!
  monthlyBudget: Float!
}

type Planning {
  _count: PlanningCount!
  amount: Float!
  categoryId: String!
  createdAt: DateTime!
  currency: String!
  date: DateTime
  description: String
  id: ID!
  monthIndex: Int!
  parentPlanning: Planning
  parentPlanningId: Int
  parentPlannings: [Planning!]
  repeat: Boolean!
  repeatedPlanning: Planning
  repeatedPlanningId: Int
  repeatedPlannings: [Planning!]
  transaction: Transaction
  transactionId: Int
  type: PlanningType!
  updatedAt: DateTime!
  user: User!
  userId: Int!
  year: Int!
}

type PlanningCount {
  parentPlannings: Int!
  repeatedPlannings: Int!
}

input PlanningInput {
  amount: Float!
  categoryId: String!
  currency: String!
  date: DateTime
  description: String
  monthIndex: Float!
  repeat: Boolean = false
  repeatedPlanningId: Float
  type: PlanningType!
  year: Float!
}

enum PlanningType {
  CATEGORY
  TRANSACTION
}

type Query {
  exchangeRate(date: DateTime!): ExchangeRate!
  exchangeRates: [ExchangeRate!]!
  me: UserWithoutPasswordModel!
  planning(monthIndex: Float!, year: Float!): [Planning!]!
  repeatingPlanning(monthIndex: Float!, year: Float!): [Planning!]!
  transactions(date: DateTime): [Transaction!]!
}

input SignInInput {
  email: String!
  password: String!
}

input SignUpInput {
  email: String!
  lang: String!
  name: String!
  password: String!
}

type Transaction {
  Planning: [Planning!]
  _count: TransactionCount!
  amount: Float!
  categoryId: String
  createdAt: DateTime!
  currency: String!
  date: DateTime!
  description: String
  exchangeRate: ExchangeRate!
  exchangeRateId: Int!
  id: ID!
  updatedAt: DateTime!
  user: User!
  userId: Int!
}

type TransactionCount {
  Planning: Int!
}

input TransactionInput {
  amount: Float!
  categoryId: String!
  currency: String!
  date: DateTime!
  description: String!
}

input UpdateProfileInput {
  currency: String
  lang: String
  monthStartDay: Float
  monthlyBudget: Float
  name: String
  newPassword: String
  oldPassword: String
}

type User {
  Planning: [Planning!]
  _count: UserCount!
  currency: String!
  email: String!
  id: ID!
  lang: String!
  monthStartDay: Int!
  monthlyBudget: Float!
  name: String!
  onboardingAt: DateTime
  password: String!
  refreshToken: String
  transaction: [Transaction!]
}

type UserCount {
  Planning: Int!
  transaction: Int!
}

type UserWithoutPasswordModel {
  currency: String!
  email: String!
  id: ID!
  lang: String
  monthStartDay: Int!
  monthlyBudget: Float!
  name: String!
  onboardingAt: DateTime
}